version: 2

sources:
  - name: neo_bank
    schema: NeoBank
    tables:
      - name: users
      - name: notifications
      - name: transactions
      - name: devices
        columns:
          - name: OS
            data_type: string
            description: string identifying the OS type use by the customer
          - name: user_id
            data_type: string
            description: string uninquely identifying the user
            tests:
              - unique:
                  column : 'user_id'